services:
  workload_a:
    build: .
    container_name: workload_a
    restart: unless-stopped
    environment:
      - CPU_MIN=10
      - CPU_MAX=15
      - MEM_MIN=5
      - MEM_MAX=10
      - CHANGE_INTERVAL=20

  workload_b:
    build: .
    container_name: workload_b
    restart: unless-stopped
    environment:
      - CPU_MIN=5
      - CPU_MAX=10
      - MEM_MIN=10
      - MEM_MAX=15
      - CHANGE_INTERVAL=20
